trigger:
  - main

stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: BuildAPI
        steps:
          - task: UseDotNet@2
            displayName: Use .NET 9 SDK
            inputs:
              version: 9.0.x

          - task: DotNetCoreCLI@2
            displayName: Build Web API
            inputs:
              command: build
              projects: 'api/CloudIEP.Web'

          - task: DotNetCoreCLI@2
            displayName: Run Unit Tests
            inputs:
              command: test
              projects: '**/*UnitTests.csproj'

      - job: BuildReact
        steps:
          - script: |
              cd cloud-iep-client
              yarn install
            displayName: yarn install

          - script: |
              cd cloud-iep-client
              yarn build
            displayName: yarn build
