trigger:
  - main

stages:
  - stage: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: BuildAPI
        steps:
          - task: UseDotNet@2
            displayName: Use .NET 5 SDK
            inputs:
              version: 5.0.x

          - task: DotNetCoreCLI@2
            displayName: Build Web API
            inputs:
              command: build
              projects: 'api/CloudIEP.Web'

          - task: DotNetCoreCLI@2
            displayName: Run Unit Tests
            inputs:
              command: test
              projects: '**/*UnitTests.csproj'

      - job: BuildReact
        steps:
          - task: Npm@1
            displayName: NPM Install
            inputs:
              workingDir: cloud-iep-client
              command: install

          - task: Npm@1
            displayName: NPM Build
            inputs:
              workingDir: cloud-iep-client
              command: custom
              customCommand: run build
